// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID               int32
	Content          string
	ThreadID         int32
	CreatorID        uuid.UUID
	CreatedTimestamp time.Time
	UpdatedTimestamp time.Time
}

type Thread struct {
	ID               int32
	Title            string
	Content          string
	CreatorID        uuid.UUID
	CreatedTimestamp time.Time
	UpdatedTimestamp time.Time
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
}
